### ISSUE TITLE
Authentication TextField Validations

### ISSUE THREAD

**Issue by missamynicholson** [missamynicholson/phlash#33]
Only allow user to enter a username of 15 chars or less.
Only allow user to enter a password and email which do not stretch beyond screen width.

The check should be both on the UITextField (i.e. stop the user actually typing more than x chars into the field), and on the pre-database check (i.e. if username chars > 15, or if email/password chars> 50, don't let signup happen).

Force lowercase for email and username.
Ensure autocorrect and autocapitalisation are turned off.

Clear UITextFields once data has been used - so that the previous entry does not appear next time.

Ensure username is alphanumeric.[a-z0-9]

**Comment by SergioETrillo** [comment]
as a developer
so that the app has sensible limits
I want to have authentication text field validations for usernames, emails and passwords
