### ISSUE TITLE
Caption validation

### ISSUE THREAD

**Issue by missamynicholson** [missamynicholson/phlash#34]
Prevent the caption entered into the UITextField from being wider than the screen bounds.

Do a pre-save check that the caption is less than 100 chars.

Make sure the caption UILabel fits the screen i.e. shrink the font size if it is wider.

If no caption is entered, do not show empty label when viewing photo

**Comment by SergioETrillo** [comment]
as a developer
so that my app has sensible limits
I want to ensure that caption does not exceed the limits and fits nicely in the screen
