### ISSUE TITLE
Fancy caption

### ISSUE THREAD

**Issue by missamynicholson** [missamynicholson/phlash#35]
Make the UITextField for caption input draggable (only in the y axis) using UIPanGestureRecognizer

Save the yValue (as a fraction of the photo height) into the database

Display the caption as a UILabel in the same place that the creator of the phlash positioned it.

Allow caption to move with the photo across the screen, as it is being sent.

Ensure that the UITextField for caption cannot be dragged further down than the senderLabel, then they don't overlap when viewing the photo. (senderLabel sits at screenBounds.height*19/20)

**Comment by SergioETrillo** [comment]
as a artistic Phlaser
so that I can create a meme style phlash
I want to be able to position my text in the taken phlash
